sudo: false
language: python
cache: pip
python:
  - "2.7"
  - "3.5"
install:
  - pip install -U pip setuptools
  - pip install tox-travis codecov
  - pip install -r requirements-dev.txt
script:
  - tox
  - py.test --cov=gym_paneldepon
after_success: codecov -e TRAVIS_PYTHON_VERSION
